//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldPC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_list
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_crash { get; set; }
        public Nullable<System.DateTime> date_repair { get; set; }
        public string reason { get; set; }
        public Nullable<int> crash_history_id { get; set; }
    
        public virtual crash_history crash_history { get; set; }
    }
}
